# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lorraine/Documents/smart

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lorraine/Documents/smart

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/lorraine/Documents/smart/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lorraine/Documents/smart/CMakeFiles /home/lorraine/Documents/smart/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lorraine/Documents/smart/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smart

# Build rule for target.
smart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smart
.PHONY : smart

# fast build rule for target.
smart/fast:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/build
.PHONY : smart/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f ext/libdivsufsort/CMakeFiles/uninstall.dir/build.make ext/libdivsufsort/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named divsufsort

# Build rule for target.
divsufsort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 divsufsort
.PHONY : divsufsort

# fast build rule for target.
divsufsort/fast:
	$(MAKE) -f ext/libdivsufsort/lib/CMakeFiles/divsufsort.dir/build.make ext/libdivsufsort/lib/CMakeFiles/divsufsort.dir/build
.PHONY : divsufsort/fast

#=============================================================================
# Target rules for targets named divsufsort64

# Build rule for target.
divsufsort64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 divsufsort64
.PHONY : divsufsort64

# fast build rule for target.
divsufsort64/fast:
	$(MAKE) -f ext/libdivsufsort/lib/CMakeFiles/divsufsort64.dir/build.make ext/libdivsufsort/lib/CMakeFiles/divsufsort64.dir/build
.PHONY : divsufsort64/fast

src/AppConfig.o: src/AppConfig.cpp.o

.PHONY : src/AppConfig.o

# target to build an object file
src/AppConfig.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/AppConfig.cpp.o
.PHONY : src/AppConfig.cpp.o

src/AppConfig.i: src/AppConfig.cpp.i

.PHONY : src/AppConfig.i

# target to preprocess a source file
src/AppConfig.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/AppConfig.cpp.i
.PHONY : src/AppConfig.cpp.i

src/AppConfig.s: src/AppConfig.cpp.s

.PHONY : src/AppConfig.s

# target to generate assembly for a file
src/AppConfig.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/AppConfig.cpp.s
.PHONY : src/AppConfig.cpp.s

src/ExactLCPk.o: src/ExactLCPk.cpp.o

.PHONY : src/ExactLCPk.o

# target to build an object file
src/ExactLCPk.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/ExactLCPk.cpp.o
.PHONY : src/ExactLCPk.cpp.o

src/ExactLCPk.i: src/ExactLCPk.cpp.i

.PHONY : src/ExactLCPk.i

# target to preprocess a source file
src/ExactLCPk.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/ExactLCPk.cpp.i
.PHONY : src/ExactLCPk.cpp.i

src/ExactLCPk.s: src/ExactLCPk.cpp.s

.PHONY : src/ExactLCPk.s

# target to generate assembly for a file
src/ExactLCPk.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/ExactLCPk.cpp.s
.PHONY : src/ExactLCPk.cpp.s

src/ReadsDB.o: src/ReadsDB.cpp.o

.PHONY : src/ReadsDB.o

# target to build an object file
src/ReadsDB.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/ReadsDB.cpp.o
.PHONY : src/ReadsDB.cpp.o

src/ReadsDB.i: src/ReadsDB.cpp.i

.PHONY : src/ReadsDB.i

# target to preprocess a source file
src/ReadsDB.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/ReadsDB.cpp.i
.PHONY : src/ReadsDB.cpp.i

src/ReadsDB.s: src/ReadsDB.cpp.s

.PHONY : src/ReadsDB.s

# target to generate assembly for a file
src/ReadsDB.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/ReadsDB.cpp.s
.PHONY : src/ReadsDB.cpp.s

src/compute_klcp.o: src/compute_klcp.cpp.o

.PHONY : src/compute_klcp.o

# target to build an object file
src/compute_klcp.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/compute_klcp.cpp.o
.PHONY : src/compute_klcp.cpp.o

src/compute_klcp.i: src/compute_klcp.cpp.i

.PHONY : src/compute_klcp.i

# target to preprocess a source file
src/compute_klcp.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/compute_klcp.cpp.i
.PHONY : src/compute_klcp.cpp.i

src/compute_klcp.s: src/compute_klcp.cpp.s

.PHONY : src/compute_klcp.s

# target to generate assembly for a file
src/compute_klcp.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/compute_klcp.cpp.s
.PHONY : src/compute_klcp.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrices.o: src/matrices.cpp.o

.PHONY : src/matrices.o

# target to build an object file
src/matrices.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/matrices.cpp.o
.PHONY : src/matrices.cpp.o

src/matrices.i: src/matrices.cpp.i

.PHONY : src/matrices.i

# target to preprocess a source file
src/matrices.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/matrices.cpp.i
.PHONY : src/matrices.cpp.i

src/matrices.s: src/matrices.cpp.s

.PHONY : src/matrices.s

# target to generate assembly for a file
src/matrices.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/matrices.cpp.s
.PHONY : src/matrices.cpp.s

src/sdsl/bits.o: src/sdsl/bits.cpp.o

.PHONY : src/sdsl/bits.o

# target to build an object file
src/sdsl/bits.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/sdsl/bits.cpp.o
.PHONY : src/sdsl/bits.cpp.o

src/sdsl/bits.i: src/sdsl/bits.cpp.i

.PHONY : src/sdsl/bits.i

# target to preprocess a source file
src/sdsl/bits.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/sdsl/bits.cpp.i
.PHONY : src/sdsl/bits.cpp.i

src/sdsl/bits.s: src/sdsl/bits.cpp.s

.PHONY : src/sdsl/bits.s

# target to generate assembly for a file
src/sdsl/bits.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/sdsl/bits.cpp.s
.PHONY : src/sdsl/bits.cpp.s

src/sdsl/construct_sa.o: src/sdsl/construct_sa.cpp.o

.PHONY : src/sdsl/construct_sa.o

# target to build an object file
src/sdsl/construct_sa.cpp.o:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/sdsl/construct_sa.cpp.o
.PHONY : src/sdsl/construct_sa.cpp.o

src/sdsl/construct_sa.i: src/sdsl/construct_sa.cpp.i

.PHONY : src/sdsl/construct_sa.i

# target to preprocess a source file
src/sdsl/construct_sa.cpp.i:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/sdsl/construct_sa.cpp.i
.PHONY : src/sdsl/construct_sa.cpp.i

src/sdsl/construct_sa.s: src/sdsl/construct_sa.cpp.s

.PHONY : src/sdsl/construct_sa.s

# target to generate assembly for a file
src/sdsl/construct_sa.cpp.s:
	$(MAKE) -f CMakeFiles/smart.dir/build.make CMakeFiles/smart.dir/src/sdsl/construct_sa.cpp.s
.PHONY : src/sdsl/construct_sa.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... smart"
	@echo "... uninstall"
	@echo "... divsufsort64"
	@echo "... divsufsort"
	@echo "... src/AppConfig.o"
	@echo "... src/AppConfig.i"
	@echo "... src/AppConfig.s"
	@echo "... src/ExactLCPk.o"
	@echo "... src/ExactLCPk.i"
	@echo "... src/ExactLCPk.s"
	@echo "... src/ReadsDB.o"
	@echo "... src/ReadsDB.i"
	@echo "... src/ReadsDB.s"
	@echo "... src/compute_klcp.o"
	@echo "... src/compute_klcp.i"
	@echo "... src/compute_klcp.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrices.o"
	@echo "... src/matrices.i"
	@echo "... src/matrices.s"
	@echo "... src/sdsl/bits.o"
	@echo "... src/sdsl/bits.i"
	@echo "... src/sdsl/bits.s"
	@echo "... src/sdsl/construct_sa.o"
	@echo "... src/sdsl/construct_sa.i"
	@echo "... src/sdsl/construct_sa.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

